server:
  port: 8081
  servlet:
    context-path: /user

spring:

  # Tắt banner
  main:
    banner-mode: off

  # Kết nối tới database
  datasource:
    url: jdbc:mysql://localhost:3308/user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "55188254cbc120b62496b2a8c7e974ca426e4579db554ff816b2fb30705b7247"
