spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/restaurants/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: payment-service
          uri: http://localhost:8084

          predicates:
            - Path=/api/payments/**
        - id: drone-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/drones/**