server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      httpclient:
        max-in-memory-size: 10485760

      routes:
        # USER SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/cart/**

        # RESTAURANT STATIC FILES
        - id: restaurant-static-assets
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/images/**
          filters:
            - RewritePath=/api/restaurants/images/(?<remaining>.*), /images/$\{remaining}

        # RESTAURANT API
        - id: restaurant-api
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/**,/api/menu-items/**

        # ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        # PAYMENT SERVICE
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        # DRONE SERVICE
        - id: drone-service
          uri: lb://DRONE-SERVICE
          predicates:
            - Path=/api/drones/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
